baseURL = 'https://pro100andrey.github.io'
languageCode = 'en-us'
title = 'Andrii Ivanov'
theme = "hello-friend-ng"
enableRobotsTXT = true
googleAnalytics = 'G-DPENQVVHDD'

[params]
# Subtitle for home
homeSubtitle = "Software Developer"

[params.logo]
logoText = "pro100.dev"

[[params.social]]
name = "github"
url = "https://github.com/pro100andrey"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/andrii-ivanov-37114286/"

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "project/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "about"
weight = 4
