baseURL = 'https://pro100andrey.github.io'
languageCode = 'en-us'
title = 'Andrey Ivanov'
theme = "hello-friend-ng"

[params]
# Subtitle for home
homeSubtitle = "Software Developer"

[params.logo]
logoText = "pro100.dev"


[[params.social]]
name = "github"
url = "https://github.com/pro100andrey"


[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/andrey-ivanov-37114286/"


[[menu.main]]
identifier = "about"
name = "About"
url = "about"
